# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Calcasieu Soccer Club"
theme = "syna"
enableGitInfo = true
version = "0.17.3"

# Google Analytics tracking
googleAnalytics = ""

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "Calcasieu Soccer Club"
  description = "Soccer club for all ages in Calcasieu parish"
  custom_css = ["/css/custom.css"]

  [params.style]
    background = "white"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "images/favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
  #  favicon_png = "favicon.png"
  #  favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#00838F"
    secondary = "#868e96"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "/about"
  name = "About Us"
  weight = 20

[[menu.main]]
  url = "/programs"
  name = "Programs"
  weight = 30

[[menu.main]]
  url = "/volunteer"
  name = "Volunteer"
  weight = 40

[[menu.main]]
  url = "/clinics"
  name = "Camps & Clinics"
  weight = 40

[[menu.main]]
  url = "/resources"
  name = "Resources"
  weight = 50

[[menu.footer]]
  url = "#programs"
  name = "Programs"
  weight = 10

[[menu.footer]]
  url = "/tournaments"
  name = "Tournaments & Clinics"
  weight = 10

[[menu.footer]]
  url = "/volunteer"
  name = "Volunteer"
  weight = 10

[[menu.footer]]
  url = "/resources"
  name = "Resources"
  weight = 10

[[menu.footer]]
  url = "#contact"
  name = "Contact"
  weight = 30


[[menu.footer_social]]
  weight = 20
  name = "facebook"
  pre = "fab fa-facebook-f"
  url = "https://www.facebook.com/CalcasieuSoccerClub"

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM)$']
  [security.funcs]
    getenv = ['^HUGO_', 'DEMO_MODE']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']